os: linux
dist: focal
language: csharp
solution: src/DbCtl.Connectors.sln
dotnet: 3.1.404

install:
  - dotnet restore
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner

script:
  - msbuild /p:Configuration=Release src/DbCtl.Connectors.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe src/DbCtl.Connectors.UnitTestsbin/Release/netstandard2.1/DbCtl.Connectors.UnitTests.dll
