os: linux
dist: bionic
language: csharp
dotnet: 3.1.404

install:
  - dotnet restore src/DbCtl.Connectors.sln
  - nuget install NUnit.Console -Version 3.11.1 -OutputDirectory testrunner

script:
  - dotnet build -c Release src/DbCtl.Connectors.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.11.1/tools/nunit3-console.exe src/DbCtl.Connectors.UnitTests/bin/Release/netcoreapp3.1/DbCtl.Connectors.UnitTests.dll

before_deploy:
- dotnet pack -c Release src/DbCtl.Connectors/DbCtl.Connectors.csproj

deploy:
  skip_cleanup: true
  provider: script
  script: nuget push src/DbCtl.Connectors/bin/Debug/DbCtl.Connectors.*.nupkg -Verbosity detailed -Source $NUGETSOURCE -ApiKey $NUGETAPIKEY --skip-duplicate
  on:
    branch: main
