os: linux
dist: bionic
language: csharp
dotnet: 3.1.404

install:
  - dotnet restore src/DbCtl.Connectors.sln

script:
  - dotnet test src/DbCtl.Connectors.UnitTests/DbCtl.Connectors.UnitTests.csproj
  - dotnet build -c Release src/DbCtl.Connectors.sln

before_deploy:
- dotnet pack -c Release src/DbCtl.Connectors/DbCtl.Connectors.csproj

deploy:
  skip_cleanup: true
  provider: script
  script: nuget push src/DbCtl.Connectors/bin/Debug/DbCtl.Connectors.*.nupkg -Verbosity detailed -Source $NUGETSOURCE -ApiKey $NUGETAPIKEY --skip-duplicate
  on:
    branch: main
