name: DbCtl.Connectors

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.x
    - name: Install dependencies
      run: dotnet restore src/DbCtl.Connectors.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore src/DbCtl.Connectors.sln
    - name: Test
      run: dotnet test --no-restore --verbosity normal src/DbCtl.Connectors.sln
